
name: .NET Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build for Windows x64
    
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Build the project
    - name: Build
      run: dotnet build ReadDown/ReadDown.csproj -c Debug -a x64
    
    # Archive the files
    #- name: Zip the files
    #  run: tar.exe -a -c -f win-debug-x64.zip $env:Binary_Directory/*
      
    # Upload output binaries
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows x64 Debug
        path: ReadDown/bin/Debug/
        